exports.handler = async (event, context) => {
   console.log("Serverless function invoked with event:", event);
   console.log("Context:", context);
    return {
      statusCode: 200,
      body: JSON.stringify({
        items: [
          {   name: "Ey Tunisie", 
            email : "eyrecruit@tn.ey.com",  
            location : "Avenue Fadhel Ben Achour Centre Urbain Nord",
              shortdescription : "Travaillant dans les domaines de l'assurance, du conseil, du droit, de la stratégie, de la fiscalité et des transactions...",
              description: "EY existe pour construire un monde du travail meilleur, en contribuant à créer de la valeur à long terme pour les clients, les personnes et la société, et en renforçant la confiance dans les marchés de capitaux.Grâce aux données et à la technologie, des équipes diversifiées d'EY dans plus de 150 pays apportent leur confiance par le biais de l'assurance et aident les clients à croître, se transformer et fonctionner.Travaillant dans les domaines de l'assurance, du conseil, du droit, de la stratégie, de la fiscalité et des transactions, les équipes d'EY posent de meilleures questions pour trouver de nouvelles réponses aux problèmes complexes auxquels notre monde est confronté aujourd'hui.",
              sujet : "",
              Images : ["https://i.ibb.co/ZgM1t6P/1634368965482.jpg","https://i.ibb.co/2WWm1vr/2023-11-10.jpg", "https://i.ibb.co/JvMwMZY/1633963575197.jpg","https://i.ibb.co/pQLcp4Y/IMG-20211119-110524.jpg",], 
              linkDin : "https://www.linkedin.com/company/ernstandyoung/posts/?feedView=all" ,
              pfeBook2023:"https://www.pfebook.com/wp-content/uploads/2023/11/STAGES-PFE-BOOK-2023-2024.pdf" , 
              pfeBook2024:"",
              web:"http://www.ey.com",
              long:"36.84444214128213",
              lat:"10.200790182220814",
           },
           {
              name: "ACTIA Engineering Services", 
              email : "contact@actia-engineering.tn",
              location : "Technopôle El Ghazala - 1, BP99 rue Newton",
              shortdescription : " spécialisée dans la conception et le développement de solutions matérielles embarquées et de services logiciels pour les secteurs de la mobilité et de l'industrie...",
              description: "La Division SERVICES D'INGÉNIERIE du Groupe français ACTIA est spécialisée dans la conception et le développement de solutions matérielles embarquées et de services logiciels pour les secteurs de la mobilité et de l'industrie.L'expertise en software et hardware de plus de 900 ingénieurs, répartis sur quatre sites autour du bassin méditerranéen – Tunis, Sfax, Toulouse et Le Caire – garantit le développement de produits et de services avec une qualité logicielle et technologique de pointe.",
              sujet : "Créée en septembre 2001, XTENSUS est une ESN spécialisée en développement de plateformes web, en exploitation de portails Internet et en édition de logiciels.",
              Images : ["https://i.ibb.co/wSL6Qfh/DSC-0618.jpg","https://i.ibb.co/qxJ6qv1/DSC-0644.jpg","https://i.ibb.co/hY42FXf/DSC-0671.jpg","https://i.ibb.co/yYFYsZC/2023-02-18.jpg"], 
              linkDin : "https://www.linkedin.com/company/actia-engineering-services/about/" ,
              pfeBook2023:"https://www.linkedin.com/posts/actia-engineering-services_pfe-book-2024safety-cybersecurity-activity-7128770437202796544-xO7Q/?utm_source=share&utm_medium=member_desktop" , 
              pfeBook2024:"",
              web:"https://lab-engineering.actia.tn/actia-engineering-services/",
              long:"36.89856776592702",
              lat:"10.18738783942121",
           },
           {
              name: "ADACTIM", 
              email : "contact@adactim.com",
              location : "Technopark El Ghazela Tunis - Tunisia Tunis، 2088",
              shortdescription : "ADACTIM est un opérateur de services managés et Cloud. Avec une expérience de plus de 25 ans au service des entreprises en Europe, Afrique et Moyen-Orient dans leur innovation digitale,",
              description: "ADACTIM fournit des solutions IT innovantes et de haute qualité, accompagnant ses clients dans leur transformation métier et technologique grâce à son expertise internationale en Cloud et Infrastructure, intégration, Sécurité et infogérance SI.",
              Images : ["https://i.ibb.co/d6NdS5w/20181213-143451.jpg","https://i.ibb.co/6D81dPh/20181213-143417.jpg","https://i.ibb.co/hF9GTsR/20181213-143925.jpg","https://i.ibb.co/yFLGgzq/Adactim.png"], 
              linkDin : "https://www.linkedin.com/company/adactis/about/" ,
              pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7138187960608264192/" , 
              pfeBook2024:"",
              web:"http://www.adactim.com",
              long:"36.897297814917394",
              lat:"10.192676152744628",
           },
           {
            name: "Orange", 
            email : "1999.info@orange.com",
            location : "Immeuble Orange, Centre Urbain Nord, 1003 Tunis, Tunisie.",
            shortdescription : "1er opérateur à obtenirla certification Gender Equality European International Standard«(GEEIS) en faveur de sa politique d’égalité professionnelle femmes-hommes ainsi que de la promotion de la femme tunisienne",
            description: "Orange est le 2ème opérateur privé de télécommunications en Tunisie et fait partie du Groupe Orange. Société de téléphonie fixe , mobile et internet présente sur le marché tunisien depuis le 5 Mai 2010, Orange Tunisie propose des lignes fixe, mobiles, de l’internet très Haut Débit 3G, de l’internet ADSL, des équipements de téléphonie mobile et de nombreux services à valeur ajoutée.",
            sujet : "",
            Images : ["https://i.postimg.cc/MHFdg6wz/orange-tunisie.png","https://i.postimg.cc/8kKK7H6x/146419784310-content.jpg"], 
            linkDin : "https://www.linkedin.com/company/orange-tunisie/" ,
            pfeBook2023:"https://drive.google.com/file/d/1p3tyzfWp82U9RSH1W_HynlCYAqqwgKr2/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.orange.tn/contact",
            long:"35.82981846490757",
            lat:"10.640741421935484",
         },
          
           {
              name: "Yess Consulting", 
              sujet : "",
              email : "contact@yess-consulting.com",
              location : " urbain nord 1083 cité el khadhra, 1003",
              shortdescription : "Yess Consulting est éditeur de progiciels intégrés de gestion, spécialisé dans le développement d'ERP depuis 2014...",
              description: "Yess Consulting est un éditeur de progiciels de gestion intégrés, spécialisé dans la conception de l'ERP YessClever. Notre équipe est constituée d'experts, de consultants et ingénieurs en nouvelles technologies, qui vous aident à atteindre vos objectifs business.Nous proposons également une multitude de services qui rallient technicité, expertise, accompagnement et maintenance.",
              Images : ["https://i.postimg.cc/wv1dcvvt/2024-08-06.jpg","https://i.ibb.co/QbwbwCh/2024-08-06-1.jpg"], 
              linkDin : "https://www.linkedin.com/company/yessconsulting/about/" ,
              pfeBook2023:"https://drive.google.com/file/d/1VTqD8Pp87MthHrc_GgUaQDQu7Hc9z4hT/view" , 
              pfeBook2024:"",
              web:"https://yess-consulting.com/",
              long:"36.844284496821665",
              lat:"10.197411757079058",
           },
           {
              name: "xtensus", 
              email : "ecrutement@xtensus.com",
              location : "Rue Omar Ibn Abdelaziz, B4-1, Ariana, Ennkhilet 2083",
              shortdescription : "Développement Web, Portail internet, Intranet, Extranet, Site Web, e-Commerce, Gestion de portails, CMS, GED, GMP : Gestion des Marchés Publics / Privés, GPR : Gestion de Parc Roulant, and GBO : Gestion de Bureau d'Ordre...",
              description: "Xtensus Tunisie est une société de développement Web, de Multimédia et d’exploitation de portails internet.  Elle offre un ensemble d’outil Web à ses clients dont un système de gestion électronique de documents (GED) et un système de gestion de contenu (CMS).  Son expertise se concentre sur le développement d’interfaces dynamiques, les systèmes sécurisés et intégrés, les plateformes modulaires, et les technologies avancées. Elle compte des clients de la Tunisie, du Canada et de la France.",
              sujet : "",
              Images : ["https://i.ibb.co/2K2mJYY/Vue-Exterieure.jpg"], 
              linkDin : "https://www.linkedin.com/company/xtensus/?originalSubdomain=tn" ,
              pfeBook2023:"https://drive.google.com/file/d/1D0sfID8IKWpY05fDbMpXa9VbQRT-HrVs/view" , 
              pfeBook2024:"",
              web:"http://www.xtensus.com",
              long:"36.884391615175346",
              lat:"10.18399702020408",
           },
           {
            name: "ADDIXO", 
            email : "contact@addixo.com",
            location : "Technopark Manouba Manouba، 2010",
            shortdescription : "ADDIXO est une entreprise d'ingénierie internationale dotée de compétences de pointe dans les domaines du numérique, du logiciel, de la mécanique, de l'automatisation et de l'intelligence artificielle...",
            description: "ADDIXO est une entreprise d'ingénierie internationale avec des compétences de premier plan dans les domaines du numérique, du logiciel, de la mécanique, de l'automatisation et de l'intelligence artificielle. Alliant une expérience inégalée et des compétences spécialisées, nous proposons la conception et la fabrication d'équipements de production intelligents, des solutions de numérisation des ateliers, ainsi que des services de R&D pour des produits et systèmes de haute qualité et compétitifs.",
            sujet : "",
            Images : ["https://i.ibb.co/pypgPzs/2024-05-22.jpg","https://i.ibb.co/9rSDZCF/2017-07-10.jpg","https://i.ibb.co/bLJNhS7/20190228-161129.jpg"], 
            linkDin : "https://www.linkedin.com/company/addixogroup/" ,
            pfeBook2023:"https://drive.google.com/file/d/1Z9HCfOiJa8g_vFsF5tvOdYMJidXlyfsE/view" , 
            pfeBook2024:"",
            web:"https://www.addixo.com/fr/",
            long:"36.807613705954026",
            lat:"10.072614224397016",
         },
         {
            name: "ADN Expertise", 
            email : "contact@adn-expertise.fr",
            location : "2eme étage, Planet food, 1 Av. de Yasser Arafat, Sousse 4050",
            shortdescription : "ADN Expertise est un cabinet de consulting en stratégies et développement IT : développement Web & Mobile, DevOps, Big Data, Méthodologie...",
            description: "ADN Expertise est un cabinet de consulting en stratégies et développement IT. Notre mission principale est de vous accompagner dans votre transformation digitale à travers une large gamme de services 4.0  : développement Web & Mobile, DevOps, Big Data, Méthodologie.. , en misant sur une équipe qui a pour devise créativité, réactivité et une approche centrée client pour assurer une transformation réussie.",
            sujet : "",
            Images : ["https://i.ibb.co/bLJNhS7/20190228-161129.jpg"], 
            linkDin : "https://www.linkedin.com/company/addixogroup/" ,
            pfeBook2023:"https://drive.google.com/file/d/1AhTQieSaBr_3H4Pk4w1Y9mMLFqQqz7C0/view" , 
            pfeBook2024:"",
            web:"http://www.adn-expertise.fr/",
            long:"35.83381981702676",
            lat:"10.590005698220123",
         },   
         {
            name: "ADP", 
            email : "enterpriselearningsupport@adp.com",
            location : "Imm Tunisia Tower, Avenue Fadhel Ben Achour, Tunis 1003",
            shortdescription : "Gestion du Capital Humain, Externalisation des processus RH (HR BPO), Services de Paie et d'Impôts, Organisation Professionnelle d'Employeurs (PEO), Retraite, Gestion des Talents, Gestion des Ressources Humaines...",
            description: "Gestion du Capital Humain, Externalisation des processus RH (HR BPO), Services de Paie et d'Impôts, Organisation Professionnelle d'Employeurs (PEO), Retraite, Gestion des Talents, Gestion des Ressources Humaines, Fiscalité et Conformité, Administration des Avantages Sociaux, Solutions de Paiement, Gestion du Temps et des Présences, Réforme des Soins de Santé, et Loi sur les Soins de Santé Abordables (ACA).",
            sujet : "",
            Images : ["https://i.ibb.co/7JCvB8K/IMG-9324.jpg","https://i.ibb.co/9csq6xM/2023-02-28.jpg","https://i.ibb.co/87VQ3zP/2023-03-01.jpg"], 
            linkDin : "https://www.linkedin.com/company/adp/life/careers/" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7137458175867301889/" , 
            pfeBook2024:"",
            web:"https://www.adp.com/",
            long:"36.84502020177994",
            lat:"10.200829258483013",
         },
         {
            name: "Agence Web AZ it", 
            email : "azit.contact@azit.fr",
            location : "BN°102, Cyber Parc, 4170",
            shortdescription : "Une agence web située en Tunisie. AZ IT est spécialisé en conception des sites internet vitrine, dynamique et e-commerce...",
            description: "Une agence web située en Tunisie. AZ IT est spécialisé en conception des sites internet vitrine, dynamique et e-commerce, le design d’identité visuelle, le référencement naturel, Community management et le développement des applications mobile",
            sujet : "",
            Images : ["https://i.ibb.co/kqzsps8/2023-11-07-1.jpg","https://i.ibb.co/fqtQMpm/cofee-agence-web-AZ-IT.jpg"], 
            linkDin : "https://www.linkedin.com/company/agencewebazit/?originalSubdomain=tn" ,
            pfeBook2023:"https://azit.fr/recrutement/" , 
            pfeBook2024:"",
            web:"http://www.azit.fr",
            long:"36.84494877349594",
            lat:"10.20084763481132",
         }, 
         {
            name: "AIESEC", 
            email : "tunisia@aiesec.net",
            location : "Manar, Tunis",
            shortdescription : "Opérant dans 127 pays et territoires, AIESEC vise à activer le leadership des jeunes en permettant aux étudiants et diplômés de gérer un programme d'échange international...",
            description: "AIESEC est la plus grande organisation mondiale dirigée par des jeunes, dédiée au développement du leadership.Opérant dans 127 pays et territoires, AIESEC vise à activer le leadership des jeunes en permettant aux étudiants et diplômés de gérer un programme d'échange international.Nous offrons à nos membres une expérience de développement intégrée, composée d'opportunités de leadership, de stages internationaux et de participation à un environnement d'apprentissage global.",
            sujet : "",
            Images : ["https://i.ibb.co/p3cjtYX/aiesec.jpg"], 
            linkDin : "https://www.linkedin.com/company/aiesec-tunisia/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/19mhj35BL_QWCayFjo1uHzkt-sx_8sH9D/view" , 
            pfeBook2024:"",
            web:"https://aiesec.org/",
            long:"33.49671458916819",
            lat:"11.115775008853188",
         },
         {
            name: "AIVENTU", 
            email : "contact@aiventu.com",
            location : "Bloc C 3ème étage، Immeuble Regency, Rue de la Feuille d'Érable, Tunis 1053",
            shortdescription : "Fort de plus de 25 ans d'expérience, Aiventu, un partenaire de confiance de 𝐌𝐢𝐜𝐫𝐨𝐬𝐨𝐟𝐭, mène des transformations digitales pour les PME et les grandes entreprises, en exploitant tout le potentiel des solutions Microsoft...",
            description: "Fort de plus de 25 ans d'expérience, Aiventu, un partenaire de confiance de 𝐌𝐢𝐜𝐫𝐨𝐬𝐨𝐟𝐭, mène des transformations digitales pour les PME et les grandes entreprises, en exploitant tout le potentiel des solutions Microsoft. Nous offrons des services de 𝐂𝐨𝐧𝐬𝐞𝐢𝐥 & 𝐂𝐨𝐧𝐬𝐮𝐥𝐭𝐢𝐧𝐠, d'𝐢𝐧𝐭𝐞𝐠𝐫𝐚𝐭𝐢𝐨𝐧 𝐝𝐞 𝐁𝐮𝐬𝐢𝐧𝐞𝐬𝐬 𝐀𝐩𝐩𝐬, ainsi que de 𝐒𝐮𝐩𝐩𝐨𝐫𝐭 & 𝐅𝐨𝐫𝐦𝐚𝐭𝐢𝐨𝐧.𝐍𝐨𝐬 𝐬𝐨𝐥𝐮𝐭𝐢𝐨𝐧𝐬 : 𝐄𝐑𝐏 :Microsoft Dynamics 365 Finance & Operations.Microsoft Dynamics 365 : . Business Central. . Gestion des Ressources Humaines. . Gestion de la Supply Chain. . Comptabilité / Finance.𝐈𝐧𝐧𝟒 𝐒𝐮𝐢𝐭𝐞.𝐃é𝐯𝐞𝐥𝐨𝐩𝐩𝐞𝐦𝐞𝐧𝐭 𝐒𝐩é𝐜𝐢𝐟𝐢𝐪𝐮𝐞.𝐆𝐄𝐃 (Gestion Électronique des Documents) & 𝐀𝐫𝐜𝐡𝐢𝐯𝐚𝐠𝐞.",
            sujet : "",
            Images : ["https://i.ibb.co/9Vr53yG/2024-04-30.jpg","https://i.ibb.co/N3PR45H/21368600-1366731463426109-2053586360729858983-o.jpg"], 
            linkDin : "https://www.linkedin.com/company/aiventu/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/posts/aiventu_catalogue-pfe-2023-2024-activity-7130123080680534017-TZG8/?utm_source=share&utm_medium=member_android" , 
            pfeBook2024:"",
            web:"http://www.aiventu.com",
            long:"36.84888883799138",
            lat:"10.27590111205327",
         },  

         {
            name: "Amaris Consulting", 
            email : "apply-tunisia@amaris. com",
            location : "Immeuble NIDA, Technopole El Ghazala Route de Raoued Km 3.5 Ariana، 2088",
            shortdescription : "Amaris Consulting est un cabinet de conseil technologique indépendant offrant des conseils et des solutions aux entreprises. Il regroupe plus de 7 600 talents issus de 110 nationalités différentes, répartis sur 5 continents et dans plus de 60 pays.",
            description: "Nous offrons des services de conseil en technologie de l'information et en stratégie technologique, ainsi que des services d'infrastructure (SI & Digital). Avec un centre d'excellence mondial dédié aux télécommunications et à la technologie, nous aidons nos clients à concevoir, structurer et exploiter leur infrastructure réseau de nouvelle génération (Télécom). Nous proposons des services aux entreprises de biotechnologie et aux industries de la santé, allant du soutien au développement de produits à l'élaboration de procédures internes (Sciences de la vie). Amaris Consulting est également un partenaire clé pour ses clients en ingénierie, fournissant l'expertise à la demande dont ils ont besoin pour continuer à faire progresser leur processus de recherche et développement (Ingénierie).",
            sujet : "",
            Images : ["https://i.ibb.co/wdkfvsh/Picture14.jpg","https://i.ibb.co/ZKZ11Hw/Picture15.jpg","https://i.ibb.co/NynfxWf/Picture16.jpg"], 
            linkDin : "https://www.linkedin.com/company/amaris/about/" ,
            pfeBook2023:"https://www.linkedin.com/jobs/view/3771391594/?alternateChannel=search&refId=qQvq2FUVHj5tMe34S%2FYbKg%3D%3D&trackingId=wufamleUIpfqMntUTXrc1Q%3D%3D&trk=d_flagship3_search_srp_jobs" , 
            pfeBook2024:"",
            web:"http://www.amaris.com",
            long:"36.89712665769107",
            lat:"10.192250070923551",
         },  
         
         
         {
            name: "AMECAP", 
            email : "contact@amecap.com",
            location : "Route de gabes, km 1 5",
            shortdescription : "Imaginez travailler avec une entreprise forte de plus de 30 ans d'expérience dans le domaine du décolletage et de l'usinage de précision. Vous seriez entouré d'une équipe hautement compétente et passionnée, constamment animée par une créativité débordante...",
            description: "Imaginez travailler avec une entreprise forte de plus de 30 ans d'expérience dans le domaine du décolletage et de l'usinage de précision. Vous seriez entouré d'une équipe hautement compétente et passionnée, constamment animée par une créativité débordante et une quête incessante d'innovation. Ensemble, nous pourrions repousser les limites, briser les conventions et créer des solutions qui changeront la donne dans votre secteur. 🚀",
            sujet : "",
            Images : ["https://i.ibb.co/JkQryLK/images.jpg"], 
            linkDin : "https://www.linkedin.com/company/amecap-tunisia/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/posts/amecap-tunisia_pfe-book-2024-amecap-activity-7133899237062254592-ZbGV/?utm_source=share&utm_medium=member_desktop" , 
            pfeBook2024:"",
            web:"http://www.amecap.tn",
            long:"34.724665823551646",
            lat:"10.74054226657982",
         },  
         {
            name: "Appaxis Innovations", 
            email : "contact@appaxisinnovations.tn",
            location : "Tunisie,Ariena Center Escalier C",
            shortdescription : "Appaxis Innovations est une entreprise spécialisée dans le développement web ,mobile et E-commerce, ainsi que dans le design avec Figma pour les nouveaux start-up.",
            description: "Appaxis Innovations est une entreprise spécialisée dans le développement web ,mobile et E-commerce, ainsi que dans le design avec Figma pour les nouveaux start-up.Nous proposons des solutions innovantes et personnalisées pour répondre à vos besoins numériques. Notre équipe d'experts est dévouée à créer des expériences en ligne exceptionnelles pour votre entreprise.",
            sujet : "",
            Images : ["https://i.ibb.co/nBFBHYL/thumbnail-logo-appaxis-75c6b87b65.jpg"], 
            linkDin : "https://www.linkedin.com/company/appaxis/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/19Z--bqIRNDSa0qe55gpkG976_B2DKFRh/view" , 
            pfeBook2024:"",
            web:"https://appaxisinnovations.tn/",
            long:"36.85802290467083",
            lat:"10.18962003507907",
         },

         {
            name: "Arcana Soft", 
            email : "contact@arcana-soft.com",
            location : "Rue D'Alexandrie, Ben Arous 2063",
            shortdescription : "Arcana est une équipe de professionnels motivés et talentueux, spécialisée dans le développement de projets web sur mesure en Tunisie... ",
            description: "Nous avons plus années d'expertiseà notre actif et nous sommes déterminés à mettre en place un system de ERP fiable et à créer des applications web , mobiles et desktop personnalisées qui répondront parfaitement aux besoins et exigences de nos clients. Nous sommes là pour accompagner nos clients à chaque étape du processus de développement, depuis la phase de test jusqu'aux premiers mois d'utilisation de l'outil. Nous sommes passionnés par notre travail et nous sommes fiers de la confiance que nos clients nous accordent",
            sujet : "",
            Images : ["https://i.ibb.co/VWCVf6c/2023-10-25.png"], 
            linkDin : "https://www.linkedin.com/company/arcana-soft/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/posts/arcana-soft_pfe-book-arcana-soft-activity-7124701118684672000-Fpu7/?utm_source=share&utm_medium=member_desktop" , 
            pfeBook2024:"",
            web:"https://arcana-soft.com/",
            long:"36.74352425539693",
            lat:"10.253877498520426",
         },
       
         {
            name: "ARSII Association", 
            email : "contact@arsii.org",
            location : "Bureau 502 - Imm. Louzir, Avenue Palestine, Sahloul Sousse, 4054",
            shortdescription : "L'Association de Recherche Scientifique et Innovation en Informatique (ARSII) est une association scientifique, fondée en mai 2016 par de jeunes enseignants-chercheurs en informatique...",
            description: "L'ARSII a pour objectif de contribuer au soutien de la recherche scientifique dans le domaine des technologies de l'information et de l'innovation, à la proposition, la supervision et le suivi de projets innovants, à la coopération et la collaboration avec les partenaires socio-économiques aux niveaux national et international, au rapprochement de la recherche scientifique et du monde académique avec l'industrie, au soutien à l'intégration des étudiants dans le milieu professionnel, ainsi qu'à l'organisation d'événements scientifiques aux niveaux national et international.",
            sujet : "",
            Images : ["https://i.ibb.co/7RkBrsF/28424070-1654050127995289-7086724902485942110-o.jpg","https://i.ibb.co/WKcTGVv/15123112-1195584257187356-4803166209063809791-o.jpg"], 
            linkDin : "https://www.linkedin.com/company/association-of-scientific-research-and-innovation-in-computer-science-arsii/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7142249308619268096/" , 
            pfeBook2024:"",
            web:"http://www.arsii.org",
            long:"35.843412154191846",
            lat:"10.595871336665608",
         },

         {
            name: "ATS - Digital Dev", 
            email : "recrutement@ats-digital.com",
            location : "Immeuble Zahra, Bloc A , Passage du lac Turkana 1053 • Les Berges du Lac",
            shortdescription : "Une start-up innovante offrant des services autour des nouvelles technologies, avec une offre autour de 4 piliers :CONSEIL ET PILOTAGE,WEB & MOBILE,DATA,OPS & CYBERSECURITY",
            description: "- CONSEIL ET PILOTAGE :  nous accompagnons nos clients à faire les bons choix pour leur transformation digitale, nous les aidons à organiser et gérer la mise en œuvre du produit (applications WEB et mobile), nous les assistons à faire évoluer leur organisation numérique - WEB & MOBILE :  nous accompagnons nos clients à concevoir, à implémenter et à maintenir des plateformes WEB et des applications mobiles répondant aux besoins, performantes et scalables - DATA : nous accompagnons nos clients à mieux gérer leurs données et à tirer profit du Big Data - OPS & CYBERSECURITY : nous accompagnons nos clients dans la mise en œuvre et l’exploitation des infrastructures Cloud avec les bonnes pratiques de sécurité",
            sujet : "",
            Images : ["https://i.ibb.co/0yMsBxT/ats-digital-dev-logo.jpg"], 
            linkDin : "https://www.linkedin.com/company/ats---digital-dev/about/" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7123625294078304256/" , 
            pfeBook2024:"",
            web:"http://www.ats-digital.com",
            long:"36.833308520806895",
            lat:"10.236281305672685",
         },


// long lat correct here !
         {
            name: "Timsoft Group", 
            email : "contact@timsoft-group.com",
            location : "Rue Lac Loch Ness, Tunis 1053 Les berges du lac 1",
            shortdescription : "Timsoft, votre partenaire clé dans la transformation digitale du Retail, excelle dans plus de 35 pays à travers le globe, fort d'une présence de proximité via nos bureaux en France, en Tunisie et au Maroc.",
            description: "Le groupe possède une vaste expérience dans les solutions logicielles B2B en tant que développeur et intégrateur d'ERP. Timsoft compte plus de 320 professionnels et plus de 1400 projets livrés. Nos 600 clients, principalement issus des secteurs du retail et de la mode, sont présents dans plus de 30 pays, avec une majorité en Europe et au Moyen-Orient.",
            sujet : "",
            Images : ["https://i.postimg.cc/N00nLz09/timsoftgroup-logo.jpg","https://i.postimg.cc/DzYMGPWC/468A0044.jpg"], 
            linkDin : "https://www.linkedin.com/company/timsoftgroup/about/" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7138522865838002178/" , 
            pfeBook2024:"",
            web:"https://timsoft-group.com/",
            long:"36.83330732262236",
            lat:"10.238547008383229",
         },


         {
            name: "PURA", 
            email : "contact.purasolutions@gmail.com",
            location : "Pôle technologique de Sousse, Route de Ceinture Sahloul",
            shortdescription : "PURA Solutions est une startup tunisienne spécialisée dans le développement de solutions matérielles et logicielles de pointe pour le secteur médical et au-delà.",
            description: "Chez PURA Solutions, notre dévouement à la technologie et à l'innovation s'étend à la création de solutions sur mesure, à la fois logicielles et matérielles, spécifiquement adaptées au secteur médical .",
            sujet : "",
            Images : ["https://i.postimg.cc/JzbG2p3F/images-1.png"], 
            linkDin : "https://www.linkedin.com/company/pura-solutions/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1xI4j6SuNOIJFv4mu0YC5HhBzaUnoXej4/view?usp=sharing" , 
            pfeBook2024:"",
            web:"http://pura-tech.com/",
            long:"35.820596961383636",
            lat:"10.593096870260121",
         },




         {
            name: "PLM RESSOURCES", 
            email : "info@allplm.com",
            location : "126 Rue IBN Khaldoun, Bizerte",
            shortdescription : "PLM RESSOURCES GMBH est une société allemande,partenaire officiel de siemens digital industries software dans l’Afrique du Nord",
            description: "PLM RESSOURCES est spécialisé dans la transformation digitale des entreprises et des institutions, et ce dans la région du Maghreb. Se structure autour d’un bureau d’étude d’ingénierie mécanique et développement informatique. Elle accompagne ses clients dans leurs transformations vers la digitalisation et l'Industrie 4.0. .",
            sujet : "",
            Images : ["https://i.postimg.cc/RZFvcGsf/2023-09-29.jpg"], 
            linkDin : "https://www.linkedin.com/company/plm-ressources-company/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1a3-YzjGcb9zHHBKmrqL-9T2a58ujFF-U/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.allplm.com/",
            long:"37.27443710184872",
            lat:"9.868745198430371",
         },






         
        ]
      })
    }
  }