exports.handler = async (event, context) => {
   console.log("Serverless function invoked with event:", event);
   console.log("Context:", context);
    return {
      statusCode: 200,
      body: JSON.stringify({
        items: [
         {
            name: "Tunisie Telecom", 
            email : "contact@tunisietelecom.tn",
            location : "Les jardins du Lac II, Tunis, 1073, TN",
            description: "Depuis sa création, Tunisie Telecom a toujours assuré son rôle en tant qu’entreprise citoyenne pour contribuer au développement durable du pays. Tunisie Telecom n’a cessé d’être proche de ses clients en assurant un support soutenu à la culture, au sport, et aux activités liées à l’environnement, l'éducation, l'entrepreneuriat, etc. Tunisie Telecom a pour vision de simplifier le quotidien de tous les tunisiens en accélérant l’adoption du Très Haut Débit et la transformation digitale de la société tunisienne. ",
            shortdescription : " Tunisie Telecom est parmi les pionniers des grands opérateurs Telecom de la région. C’est l’opérateur historique en Tunisie (plus de 150 ans). Tunisie Telecom offre des services de communication (téléphonie fixe, mobile et Internet) au grand public, entreprises, FSI et opérateurs tiers…",

            sujet : "",
            Images : ["https://i.postimg.cc/nLLZmTVc/tt-2-jpg.webp"], 
            linkDin : "https://www.linkedin.com/company/tunisie-t-l-com/" ,
            pfeBook2023:"https://drive.google.com/file/d/1sFtAsl8PqUvDlDHaC-5oo9RtIN2EmIi2/view" , 
            pfeBook2024:"https://www.linkedin.com/posts/tunisie-t-l-com_pfe-book-2024-2025-activity-7258419340645941248-ECmj?utm_source=share&utm_medium=member_desktop",
            web:"https://www.tunisietelecom.tn/particulier/",
            long:"36.772441665541116",
            lat:"10.273378702348445",
         },


         {
            name: "YEAH", 
            email : "YECIN@INKLINK.FR",
            location : "rue Omar Kaddeh, Tunis, Tunis 1073, TN",
            shortdescription : "Yeah est une entreprise en pleine expansion, dédiée à vous aider à maîtriser vos coûts de production grâce à l'externalisation stratégique des tâches administratives et de création de contenu.",
            description: "Nous sommes les pionniers du marketing d'influence en 3D sur la plateforme révolutionnaire VU (Virtuelle You). Imaginez des personnages 3D d'un réalisme captivant, promouvant vos produits ou services au sein d'une bibliothèque médiatique numérique innovante. C'est la tendance marketing ultime pour propulser votre entreprise vers des sommets inédits.",
            sujet : "",
            Images : ["https://i.postimg.cc/V6tNNMbP/yeah-production-logo.jpg"], 
            linkDin : "https://www.linkedin.com/company/yeahunivers/" ,
            pfeBook2023:"" , 
            pfeBook2024:"https://www.linkedin.com/posts/yeahunivers_envie-de-booster-votre-carri%C3%A8re-activity-7257092259022598144-LN3P?utm_source=share&utm_medium=member_desktop",
            web:"https://www.linkedin.com/company/yeahunivers/posts/?feedView=all",
            long:"36.823082870903285",
            lat:"10.193192734890864",
         },
         {
            name: "NEXT GENERATION IT", 
            email : "contact@ngit.tn",
            location : "Immeuble Montplaisir Center, Rue Ibn Nadim، Tunis 1073, Tunis, 1082, TN",
            shortdescription : "Next Generation IT est une entreprise spécialisée dans la création et la mise à jour de sites web, ainsi que dans le développement d'applications web et mobiles. Forte de compétences en développement et en art graphique, notre mission est de vous offrir des solutions digitales personnalisées et adaptées à vos besoins.",
            description: "Depuis notre création, nous nous engageons à fournir des services de qualité qui allient innovation et expertise technique. Que vous souhaitiez développer un nouveau site web, une application mobile, ou mettre à jour une plateforme existante, notre équipe d'experts est là pour vous accompagner à chaque étape de votre projet.",
            sujet : "",
            Images : ["https://i.postimg.cc/NMwHDypk/images-6.jpg"], 
            linkDin : "https://www.linkedin.com/company/nextgenerationit/posts/?feedView=all" ,
            pfeBook2023:"" , 
            pfeBook2024:"https://www.linkedin.com/posts/nextgenerationit_catalogue-des-projets-de-fin-d%C3%A9tudes-activity-7257303383584243712-NYRl?utm_source=share&utm_medium=member_desktop",
            web:"https://www.ngit.tn/",
            long:"36.818608387135285",
            lat:"10.18501288389218",
         },
         {
            name: "WeFactory", 
            email : "support@wefactorytech.tech",
            location : "7 Av farhat hached, ezzahra, ben arous 2034, TN",
            shortdescription : "WeFactory est une usine digitale spécialisée dans le développement interne d'applications web adaptées à l'intégration mobile. Nous concevons des solutions logicielles innovantes et évolutives qui connectent de manière transparente les plateformes web aux smartphones, en les proposant sous forme de produits SaaS.",
            description: "WeFactory est une usine digitale spécialisée dans le développement interne d'applications web adaptées à l'intégration mobile. Nous concevons des solutions logicielles innovantes et évolutives qui connectent de manière transparente les plateformes web aux smartphones, en les proposant sous forme de produits SaaS. Notre priorité est d'améliorer l'accessibilité et l'expérience utilisateur grâce à des applications web performantes et optimisées pour le mobile.",
            sujet : "",
            Images : ["https://i.postimg.cc/v8nFrD4T/1729320100780.jpg"], 
            linkDin : "https://www.linkedin.com/company/wefactorytech/posts/?feedView=all" ,
            pfeBook2023:"" , 
            pfeBook2024:"https://www.linkedin.com/posts/wefactorytech_wefactory-pfe-book-activity-7257327406217105408-C8KM?utm_source=share&utm_medium=member_desktop",
            web:"https://wefactory.tech/",
            long:"36.746596",
            lat:"10.305329",
         },
         {
            name: "Olindas", 
            email : "career@olindias.com",
            location : "Place du Savoir, Monastir, 5000, TN",
            shortdescription : "Notre IA de matchmaking naturel est conçue pour comprendre les intentions et les perspectives des utilisateurs. Elle saisit ce qu’ils veulent dire lorsqu'ils recherchent quelque chose et anticipe ce qu'ils cherchent, afin de leur recommander la solution la plus adaptée.",
            description: "Notre IA de matchmaking naturel est conçue pour comprendre les intentions et les perspectives des utilisateurs. Elle saisit ce qu’ils veulent dire lorsqu'ils recherchent quelque chose et anticipe ce qu'ils cherchent, afin de leur recommander la solution la plus adaptée. Découvrez comment intégrer notre modèle d'IA de matchmaking naturel dans votre entreprise. Que vous lanciez un nouveau produit ou ayez des idées innovantes prêtes à briller, nos experts sont là pour vous accompagner. Réservez une réunion Zoom dès maintenant et explorez comment notre IA de matchmaking naturel peut transformer le monde.",
            sujet : "",
            Images : ["https://i.postimg.cc/zGLkhYcw/olindias.png"], 
            linkDin : "https://www.linkedin.com/company/olindias/?originalSubdomain=tn" ,
            pfeBook2023:"" , 
            pfeBook2024:"https://www.linkedin.com/posts/olindias_end-of-study-internship-opportunity-activity-7251955753182224384-VTUB?utm_source=share&utm_medium=member_desktop",
            web:"https://www.olindias.com/",
            long:"35.76689902965428",
            lat:"10.831989933911313",
         },
         {
            name: "Keyrus", 
            email : "customersupport@keyrus.com",
            location : "Immeuble Zahra, Bloc A , Passage du lac Turkana 1053 • Les Berges du Lac",
            shortdescription : "Chez Keyrus MEA, nous bâtissons une culture où des personnes talentueuses (comme vous) peuvent donner le meilleur d'elles-mêmes. Si vous êtes prêt(e) à développer votre carrière et à tirer le meilleur parti de l'industrie des données et du digital, vous êtes au bon endroit.",
            description: "Rejoindre Keyrus MEA, c'est avoir l'opportunité de révéler vos talents et de déployer tout votre potentiel en participant à des projets stratégiques, opérationnels et technologiques pour les plus grandes entreprises françaises et internationales. C’est aussi être au cœur de l’innovation en bénéficiant de l’expertise d’un acteur international dans l'Intelligence des données, le Digital, le Conseil en management et la Transformation des entreprises Vous aurez la chance d'évoluer dans un environnement multiculturel, stimulant et formateur, où nous accordons une attention particulière à votre développement personnel et professionnel.é",
            sujet : "",
            Images : ["https://i.postimg.cc/KcNs205y/images-4.png"], 
            linkDin : "https://www.linkedin.com/company/keyrus/posts/?feedView=all" ,
            pfeBook2023:"" , 
            pfeBook2024:"https://jobs.keyrus.tn/jobs/5115319-pfe-keyrus-2025",
            web:"https://jobs.keyrus.tn/",
            long:"36.833308520806895",
            lat:"10.236281305672685",
         },
         {
            name: "ATS - Digital Dev", 
            email : "recrutement@ats-digital.com",
            location : "Immeuble Zahra, Bloc A , Passage du lac Turkana 1053 • Les Berges du Lac",
            shortdescription : "Une start-up innovante offrant des services autour des nouvelles technologies, avec une offre autour de 4 piliers :CONSEIL ET PILOTAGE,WEB & MOBILE,DATA,OPS & CYBERSECURITY",
            description: "- CONSEIL ET PILOTAGE :  nous accompagnons nos clients à faire les bons choix pour leur transformation digitale, nous les aidons à organiser et gérer la mise en œuvre du produit (applications WEB et mobile), nous les assistons à faire évoluer leur organisation numérique - WEB & MOBILE :  nous accompagnons nos clients à concevoir, à implémenter et à maintenir des plateformes WEB et des applications mobiles répondant aux besoins, performantes et scalables - DATA : nous accompagnons nos clients à mieux gérer leurs données et à tirer profit du Big Data - OPS & CYBERSECURITY : nous accompagnons nos clients dans la mise en œuvre et l’exploitation des infrastructures Cloud avec les bonnes pratiques de sécurité",
            sujet : "",
            Images : ["https://i.ibb.co/0yMsBxT/ats-digital-dev-logo.jpg"], 
            linkDin : "https://www.linkedin.com/company/ats---digital-dev/about/" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7123625294078304256/" , 
            pfeBook2024:"https://www.linkedin.com/feed/update/urn:li:activity:7246564406350761985/",
            web:"http://www.ats-digital.com",
            long:"36.833308520806895",
            lat:"10.236281305672685",
         },
         {   name: "Decade", 
              email : "recrutement@decade.fr",  
              location : "Immeuble Le Montplaisir Avenue Kheireddine Pacha Montplaisir , Tunis, Tunis 1073, TN",
              shortdescription : "Fondée en 1988, DECADE se positionne dans l’accompagnement des entreprises et enseignes de commerce « traditionnel » qui se lancent ou évoluent dans l’aventure de l’e-commerce, et qui veulent y faire rayonner leur propre modèle de développement.",
              description: "DECADE intervient en maîtrise d'œuvre (développement et intégration de solutions e-commerce), avec une offre centrée sur la fiabilisation des projets e-commerce aux différents stades de leur évolution : préparation, lancement, développement, maintenance, renouvellement, refondation, prise de recul stratégique. Pour maîtriser les risques et réunir les conditions de réussite des projets, DECADE s’appuie sur son tissu d’expériences et de compétences, portées par ses équipes et par tout un réseau de solutions et partenaires spécialisés (Mirakl, Hybris, Magento, Target2Sell, Sitecore, Microsoft, Sparkow, etc.).",
              sujet : "",
              Images : ["https://i.postimg.cc/cLRBKMNX/decade-logo.jpg"], 
              linkDin : "https://www.linkedin.com/company/decade/about/" ,
              pfeBook2023:"" , 
              pfeBook2024:"https://taleez.com/apply/stagiaire-en-projet-de-fin-d-etudes-2025-tunisie-decade",
              web:"https://www.decade.fr/notre-entreprise/sites/decade-tunis/",
              long:"36.82068747042704",
              lat:"10.191758924299595",
           },

         {   name: "Efrekiadev", 
            email : "contact@efrekiadev.com",  
            location : "Monastir, R6 Monastir centre medicale EYA",
              shortdescription : "Agence web Tunisienne spécialisée dans la création de sites web. De même que, nous sommes Spécialisés aussi dans le marketing Digitale. ",
              description: "Agence web Tunisienne spécialisée dans la création de sites web. De même que, nous sommes Spécialisés aussi dans le marketing Digitale. Ainsi que dans le développement web sur mesure. Encore, nous assurons la création de site e-commerce, site vitrine et les sites web dynamiques. EFREKIADEV, facilite votre transformation digitale marketing. Ainsi que, grâce à notre expertise en développement web, nous assurons la création des solutions web performantes et suivant les normes du web 2.0. De ce fait, nos services varient de la création de marketplace, jusqu'au développement d’application web. Ainsi qu’une grande expertise en référencement naturel, ce qui fait de nous aussi une agence SEO et agence SEA.",
              sujet : "",
              Images : ["https://i.postimg.cc/y6n8QqYK/images-4.jpg"], 
              linkDin : "https://www.linkedin.com/company/efrekiadev/?originalSubdomain=tn" ,
              pfeBook2023:"" , 
              pfeBook2024:"https://www.linkedin.com/posts/tarek-ben-regaya_book-pfe-activity-7251209412483108864-s5LM/?utm_source=share&utm_medium=member_desktop",
              web:"https://efrekiadev.com/",
              long:"35.76696649545069",
              lat:"10.83202286698005",
           },
          {   name: "Ey Tunisie", 
            email : "eyrecruit@tn.ey.com",  
            location : "Avenue Fadhel Ben Achour Centre Urbain Nord",
              shortdescription : "Travaillant dans les domaines de l'assurance, du conseil, du droit, de la stratégie, de la fiscalité et des transactions...",
              description: "EY existe pour construire un monde du travail meilleur, en contribuant à créer de la valeur à long terme pour les clients, les personnes et la société, et en renforçant la confiance dans les marchés de capitaux.Grâce aux données et à la technologie, des équipes diversifiées d'EY dans plus de 150 pays apportent leur confiance par le biais de l'assurance et aident les clients à croître, se transformer et fonctionner.Travaillant dans les domaines de l'assurance, du conseil, du droit, de la stratégie, de la fiscalité et des transactions, les équipes d'EY posent de meilleures questions pour trouver de nouvelles réponses aux problèmes complexes auxquels notre monde est confronté aujourd'hui.",
              sujet : "",
              Images : ["https://i.ibb.co/ZgM1t6P/1634368965482.jpg","https://i.ibb.co/2WWm1vr/2023-11-10.jpg", "https://i.ibb.co/JvMwMZY/1633963575197.jpg","https://i.ibb.co/pQLcp4Y/IMG-20211119-110524.jpg",], 
              linkDin : "https://www.linkedin.com/company/ernstandyoung/posts/?feedView=all" ,
              pfeBook2023:"https://www.pfebook.com/wp-content/uploads/2023/11/STAGES-PFE-BOOK-2023-2024.pdf" , 
              pfeBook2024:"",
              web:"http://www.ey.com",
              long:"36.84444214128213",
              lat:"10.200790182220814",
           },
           {
              name: "ACTIA Engineering Services", 
              email : "contact@actia-engineering.tn",
              location : "Technopôle El Ghazala - 1, BP99 rue Newton",
              shortdescription : " spécialisée dans la conception et le développement de solutions matérielles embarquées et de services logiciels pour les secteurs de la mobilité et de l'industrie...",
              description: "La Division SERVICES D'INGÉNIERIE du Groupe français ACTIA est spécialisée dans la conception et le développement de solutions matérielles embarquées et de services logiciels pour les secteurs de la mobilité et de l'industrie.L'expertise en software et hardware de plus de 900 ingénieurs, répartis sur quatre sites autour du bassin méditerranéen – Tunis, Sfax, Toulouse et Le Caire – garantit le développement de produits et de services avec une qualité logicielle et technologique de pointe.",
              sujet : "Créée en septembre 2001, XTENSUS est une ESN spécialisée en développement de plateformes web, en exploitation de portails Internet et en édition de logiciels.",
              Images : ["https://i.ibb.co/wSL6Qfh/DSC-0618.jpg","https://i.ibb.co/qxJ6qv1/DSC-0644.jpg","https://i.ibb.co/hY42FXf/DSC-0671.jpg","https://i.ibb.co/yYFYsZC/2023-02-18.jpg"], 
              linkDin : "https://www.linkedin.com/company/actia-engineering-services/about/" ,
              pfeBook2023:"https://www.linkedin.com/posts/actia-engineering-services_pfe-book-2024safety-cybersecurity-activity-7128770437202796544-xO7Q/?utm_source=share&utm_medium=member_desktop" , 
              pfeBook2024:"",
              web:"https://lab-engineering.actia.tn/actia-engineering-services/",
              long:"36.89856776592702",
              lat:"10.18738783942121",
           },
           {
              name: "ADACTIM", 
              email : "contact@adactim.com",
              location : "Technopark El Ghazela Tunis - Tunisia Tunis، 2088",
              shortdescription : "ADACTIM est un opérateur de services managés et Cloud. Avec une expérience de plus de 25 ans au service des entreprises en Europe, Afrique et Moyen-Orient dans leur innovation digitale,",
              description: "ADACTIM fournit des solutions IT innovantes et de haute qualité, accompagnant ses clients dans leur transformation métier et technologique grâce à son expertise internationale en Cloud et Infrastructure, intégration, Sécurité et infogérance SI.",
              Images : ["https://i.ibb.co/d6NdS5w/20181213-143451.jpg","https://i.ibb.co/6D81dPh/20181213-143417.jpg","https://i.ibb.co/hF9GTsR/20181213-143925.jpg","https://i.ibb.co/yFLGgzq/Adactim.png"], 
              linkDin : "https://www.linkedin.com/company/adactis/about/" ,
              pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7138187960608264192/" , 
              pfeBook2024:"",
              web:"http://www.adactim.com",
              long:"36.897297814917394",
              lat:"10.192676152744628",
           },
           {
            name: "Orange", 
            email : "1999.info@orange.com",
            location : "Immeuble Orange, Centre Urbain Nord, 1003 Tunis, Tunisie.",
            shortdescription : "1er opérateur à obtenirla certification Gender Equality European International Standard«(GEEIS) en faveur de sa politique d’égalité professionnelle femmes-hommes ainsi que de la promotion de la femme tunisienne",
            description: "Orange est le 2ème opérateur privé de télécommunications en Tunisie et fait partie du Groupe Orange. Société de téléphonie fixe , mobile et internet présente sur le marché tunisien depuis le 5 Mai 2010, Orange Tunisie propose des lignes fixe, mobiles, de l’internet très Haut Débit 3G, de l’internet ADSL, des équipements de téléphonie mobile et de nombreux services à valeur ajoutée.",
            sujet : "",
            Images : ["https://i.postimg.cc/MHFdg6wz/orange-tunisie.png","https://i.postimg.cc/8kKK7H6x/146419784310-content.jpg"], 
            linkDin : "https://www.linkedin.com/company/orange-tunisie/" ,
            pfeBook2023:"https://drive.google.com/file/d/1p3tyzfWp82U9RSH1W_HynlCYAqqwgKr2/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.orange.tn/contact",
            long:"35.82981846490757",
            lat:"10.640741421935484",
         },
          
           {
              name: "Yess Consulting", 
              sujet : "",
              email : "contact@yess-consulting.com",
              location : " urbain nord 1083 cité el khadhra, 1003",
              shortdescription : "Yess Consulting est éditeur de progiciels intégrés de gestion, spécialisé dans le développement d'ERP depuis 2014...",
              description: "Yess Consulting est un éditeur de progiciels de gestion intégrés, spécialisé dans la conception de l'ERP YessClever. Notre équipe est constituée d'experts, de consultants et ingénieurs en nouvelles technologies, qui vous aident à atteindre vos objectifs business.Nous proposons également une multitude de services qui rallient technicité, expertise, accompagnement et maintenance.",
              Images : ["https://i.postimg.cc/wv1dcvvt/2024-08-06.jpg","https://i.ibb.co/QbwbwCh/2024-08-06-1.jpg"], 
              linkDin : "https://www.linkedin.com/company/yessconsulting/about/" ,
              pfeBook2023:"https://drive.google.com/file/d/1VTqD8Pp87MthHrc_GgUaQDQu7Hc9z4hT/view" , 
              pfeBook2024:"",
              web:"https://yess-consulting.com/",
              long:"36.844284496821665",
              lat:"10.197411757079058",
           },
           {
              name: "xtensus", 
              email : "ecrutement@xtensus.com",
              location : "Rue Omar Ibn Abdelaziz, B4-1, Ariana, Ennkhilet 2083",
              shortdescription : "Développement Web, Portail internet, Intranet, Extranet, Site Web, e-Commerce, Gestion de portails, CMS, GED, GMP : Gestion des Marchés Publics / Privés, GPR : Gestion de Parc Roulant, and GBO : Gestion de Bureau d'Ordre...",
              description: "Xtensus Tunisie est une société de développement Web, de Multimédia et d’exploitation de portails internet.  Elle offre un ensemble d’outil Web à ses clients dont un système de gestion électronique de documents (GED) et un système de gestion de contenu (CMS).  Son expertise se concentre sur le développement d’interfaces dynamiques, les systèmes sécurisés et intégrés, les plateformes modulaires, et les technologies avancées. Elle compte des clients de la Tunisie, du Canada et de la France.",
              sujet : "",
              Images : ["https://i.ibb.co/2K2mJYY/Vue-Exterieure.jpg"], 
              linkDin : "https://www.linkedin.com/company/xtensus/?originalSubdomain=tn" ,
              pfeBook2023:"https://drive.google.com/file/d/1D0sfID8IKWpY05fDbMpXa9VbQRT-HrVs/view" , 
              pfeBook2024:"",
              web:"http://www.xtensus.com",
              long:"36.884391615175346",
              lat:"10.18399702020408",
           },
           {
            name: "ADDIXO", 
            email : "contact@addixo.com",
            location : "Technopark Manouba Manouba، 2010",
            shortdescription : "ADDIXO est une entreprise d'ingénierie internationale dotée de compétences de pointe dans les domaines du numérique, du logiciel, de la mécanique, de l'automatisation et de l'intelligence artificielle...",
            description: "ADDIXO est une entreprise d'ingénierie internationale avec des compétences de premier plan dans les domaines du numérique, du logiciel, de la mécanique, de l'automatisation et de l'intelligence artificielle. Alliant une expérience inégalée et des compétences spécialisées, nous proposons la conception et la fabrication d'équipements de production intelligents, des solutions de numérisation des ateliers, ainsi que des services de R&D pour des produits et systèmes de haute qualité et compétitifs.",
            sujet : "",
            Images : ["https://i.ibb.co/pypgPzs/2024-05-22.jpg","https://i.ibb.co/9rSDZCF/2017-07-10.jpg","https://i.ibb.co/bLJNhS7/20190228-161129.jpg"], 
            linkDin : "https://www.linkedin.com/company/addixogroup/" ,
            pfeBook2023:"https://drive.google.com/file/d/1Z9HCfOiJa8g_vFsF5tvOdYMJidXlyfsE/view" , 
            pfeBook2024:"",
            web:"https://www.addixo.com/fr/",
            long:"36.807613705954026",
            lat:"10.072614224397016",
         },
         {
            name: "ADN Expertise", 
            email : "contact@adn-expertise.fr",
            location : "2eme étage, Planet food, 1 Av. de Yasser Arafat, Sousse 4050",
            shortdescription : "ADN Expertise est un cabinet de consulting en stratégies et développement IT : développement Web & Mobile, DevOps, Big Data, Méthodologie...",
            description: "ADN Expertise est un cabinet de consulting en stratégies et développement IT. Notre mission principale est de vous accompagner dans votre transformation digitale à travers une large gamme de services 4.0  : développement Web & Mobile, DevOps, Big Data, Méthodologie.. , en misant sur une équipe qui a pour devise créativité, réactivité et une approche centrée client pour assurer une transformation réussie.",
            sujet : "",
            Images : ["https://i.ibb.co/bLJNhS7/20190228-161129.jpg"], 
            linkDin : "https://www.linkedin.com/company/addixogroup/" ,
            pfeBook2023:"https://drive.google.com/file/d/1AhTQieSaBr_3H4Pk4w1Y9mMLFqQqz7C0/view" , 
            pfeBook2024:"",
            web:"http://www.adn-expertise.fr/",
            long:"35.83381981702676",
            lat:"10.590005698220123",
         },   
         {
            name: "ADP", 
            email : "enterpriselearningsupport@adp.com",
            location : "Imm Tunisia Tower, Avenue Fadhel Ben Achour, Tunis 1003",
            shortdescription : "Gestion du Capital Humain, Externalisation des processus RH (HR BPO), Services de Paie et d'Impôts, Organisation Professionnelle d'Employeurs (PEO), Retraite, Gestion des Talents, Gestion des Ressources Humaines...",
            description: "Gestion du Capital Humain, Externalisation des processus RH (HR BPO), Services de Paie et d'Impôts, Organisation Professionnelle d'Employeurs (PEO), Retraite, Gestion des Talents, Gestion des Ressources Humaines, Fiscalité et Conformité, Administration des Avantages Sociaux, Solutions de Paiement, Gestion du Temps et des Présences, Réforme des Soins de Santé, et Loi sur les Soins de Santé Abordables (ACA).",
            sujet : "",
            Images : ["https://i.ibb.co/7JCvB8K/IMG-9324.jpg","https://i.ibb.co/9csq6xM/2023-02-28.jpg","https://i.ibb.co/87VQ3zP/2023-03-01.jpg"], 
            linkDin : "https://www.linkedin.com/company/adp/life/careers/" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7137458175867301889/" , 
            pfeBook2024:"",
            web:"https://www.adp.com/",
            long:"36.84502020177994",
            lat:"10.200829258483013",
         },
         {
            name: "Agence Web AZ it", 
            email : "azit.contact@azit.fr",
            location : "BN°102, Cyber Parc, 4170",
            shortdescription : "Une agence web située en Tunisie. AZ IT est spécialisé en conception des sites internet vitrine, dynamique et e-commerce...",
            description: "Une agence web située en Tunisie. AZ IT est spécialisé en conception des sites internet vitrine, dynamique et e-commerce, le design d’identité visuelle, le référencement naturel, Community management et le développement des applications mobile",
            sujet : "",
            Images : ["https://i.ibb.co/kqzsps8/2023-11-07-1.jpg","https://i.ibb.co/fqtQMpm/cofee-agence-web-AZ-IT.jpg"], 
            linkDin : "https://www.linkedin.com/company/agencewebazit/?originalSubdomain=tn" ,
            pfeBook2023:"https://azit.fr/recrutement/" , 
            pfeBook2024:"",
            web:"http://www.azit.fr",
            long:"36.84494877349594",
            lat:"10.20084763481132",
         }, 
         {
            name: "AIESEC", 
            email : "tunisia@aiesec.net",
            location : "Manar, Tunis",
            shortdescription : "Opérant dans 127 pays et territoires, AIESEC vise à activer le leadership des jeunes en permettant aux étudiants et diplômés de gérer un programme d'échange international...",
            description: "AIESEC est la plus grande organisation mondiale dirigée par des jeunes, dédiée au développement du leadership.Opérant dans 127 pays et territoires, AIESEC vise à activer le leadership des jeunes en permettant aux étudiants et diplômés de gérer un programme d'échange international.Nous offrons à nos membres une expérience de développement intégrée, composée d'opportunités de leadership, de stages internationaux et de participation à un environnement d'apprentissage global.",
            sujet : "",
            Images : ["https://i.ibb.co/p3cjtYX/aiesec.jpg"], 
            linkDin : "https://www.linkedin.com/company/aiesec-tunisia/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/19mhj35BL_QWCayFjo1uHzkt-sx_8sH9D/view" , 
            pfeBook2024:"",
            web:"https://aiesec.org/",
            long:"33.49671458916819",
            lat:"11.115775008853188",
         },
         {
            name: "AIVENTU", 
            email : "contact@aiventu.com",
            location : "Bloc C 3ème étage، Immeuble Regency, Rue de la Feuille d'Érable, Tunis 1053",
            shortdescription : "Fort de plus de 25 ans d'expérience, Aiventu, un partenaire de confiance de 𝐌𝐢𝐜𝐫𝐨𝐬𝐨𝐟𝐭, mène des transformations digitales pour les PME et les grandes entreprises, en exploitant tout le potentiel des solutions Microsoft...",
            description: "Fort de plus de 25 ans d'expérience, Aiventu, un partenaire de confiance de 𝐌𝐢𝐜𝐫𝐨𝐬𝐨𝐟𝐭, mène des transformations digitales pour les PME et les grandes entreprises, en exploitant tout le potentiel des solutions Microsoft. Nous offrons des services de 𝐂𝐨𝐧𝐬𝐞𝐢𝐥 & 𝐂𝐨𝐧𝐬𝐮𝐥𝐭𝐢𝐧𝐠, d'𝐢𝐧𝐭𝐞𝐠𝐫𝐚𝐭𝐢𝐨𝐧 𝐝𝐞 𝐁𝐮𝐬𝐢𝐧𝐞𝐬𝐬 𝐀𝐩𝐩𝐬, ainsi que de 𝐒𝐮𝐩𝐩𝐨𝐫𝐭 & 𝐅𝐨𝐫𝐦𝐚𝐭𝐢𝐨𝐧.𝐍𝐨𝐬 𝐬𝐨𝐥𝐮𝐭𝐢𝐨𝐧𝐬 : 𝐄𝐑𝐏 :Microsoft Dynamics 365 Finance & Operations.Microsoft Dynamics 365 : . Business Central. . Gestion des Ressources Humaines. . Gestion de la Supply Chain. . Comptabilité / Finance.𝐈𝐧𝐧𝟒 𝐒𝐮𝐢𝐭𝐞.𝐃é𝐯𝐞𝐥𝐨𝐩𝐩𝐞𝐦𝐞𝐧𝐭 𝐒𝐩é𝐜𝐢𝐟𝐢𝐪𝐮𝐞.𝐆𝐄𝐃 (Gestion Électronique des Documents) & 𝐀𝐫𝐜𝐡𝐢𝐯𝐚𝐠𝐞.",
            sujet : "",
            Images : ["https://i.ibb.co/9Vr53yG/2024-04-30.jpg","https://i.ibb.co/N3PR45H/21368600-1366731463426109-2053586360729858983-o.jpg"], 
            linkDin : "https://www.linkedin.com/company/aiventu/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/posts/aiventu_catalogue-pfe-2023-2024-activity-7130123080680534017-TZG8/?utm_source=share&utm_medium=member_android" , 
            pfeBook2024:"",
            web:"http://www.aiventu.com",
            long:"36.84888883799138",
            lat:"10.27590111205327",
         },  

         {
            name: "Amaris Consulting", 
            email : "apply-tunisia@amaris. com",
            location : "Immeuble NIDA, Technopole El Ghazala Route de Raoued Km 3.5 Ariana، 2088",
            shortdescription : "Amaris Consulting est un cabinet de conseil technologique indépendant offrant des conseils et des solutions aux entreprises. Il regroupe plus de 7 600 talents issus de 110 nationalités différentes, répartis sur 5 continents et dans plus de 60 pays.",
            description: "Nous offrons des services de conseil en technologie de l'information et en stratégie technologique, ainsi que des services d'infrastructure (SI & Digital). Avec un centre d'excellence mondial dédié aux télécommunications et à la technologie, nous aidons nos clients à concevoir, structurer et exploiter leur infrastructure réseau de nouvelle génération (Télécom). Nous proposons des services aux entreprises de biotechnologie et aux industries de la santé, allant du soutien au développement de produits à l'élaboration de procédures internes (Sciences de la vie). Amaris Consulting est également un partenaire clé pour ses clients en ingénierie, fournissant l'expertise à la demande dont ils ont besoin pour continuer à faire progresser leur processus de recherche et développement (Ingénierie).",
            sujet : "",
            Images : ["https://i.ibb.co/wdkfvsh/Picture14.jpg","https://i.ibb.co/ZKZ11Hw/Picture15.jpg","https://i.ibb.co/NynfxWf/Picture16.jpg"], 
            linkDin : "https://www.linkedin.com/company/amaris/about/" ,
            pfeBook2023:"https://www.linkedin.com/jobs/view/3771391594/?alternateChannel=search&refId=qQvq2FUVHj5tMe34S%2FYbKg%3D%3D&trackingId=wufamleUIpfqMntUTXrc1Q%3D%3D&trk=d_flagship3_search_srp_jobs" , 
            pfeBook2024:"",
            web:"http://www.amaris.com",
            long:"36.89712665769107",
            lat:"10.192250070923551",
         },  
         
         
         {
            name: "AMECAP", 
            email : "contact@amecap.com",
            location : "Route de gabes, km 1 5",
            shortdescription : "Imaginez travailler avec une entreprise forte de plus de 30 ans d'expérience dans le domaine du décolletage et de l'usinage de précision. Vous seriez entouré d'une équipe hautement compétente et passionnée, constamment animée par une créativité débordante...",
            description: "Imaginez travailler avec une entreprise forte de plus de 30 ans d'expérience dans le domaine du décolletage et de l'usinage de précision. Vous seriez entouré d'une équipe hautement compétente et passionnée, constamment animée par une créativité débordante et une quête incessante d'innovation. Ensemble, nous pourrions repousser les limites, briser les conventions et créer des solutions qui changeront la donne dans votre secteur. 🚀",
            sujet : "",
            Images : ["https://i.ibb.co/JkQryLK/images.jpg"], 
            linkDin : "https://www.linkedin.com/company/amecap-tunisia/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/posts/amecap-tunisia_pfe-book-2024-amecap-activity-7133899237062254592-ZbGV/?utm_source=share&utm_medium=member_desktop" , 
            pfeBook2024:"",
            web:"http://www.amecap.tn",
            long:"34.724665823551646",
            lat:"10.74054226657982",
         },  
         {
            name: "Appaxis Innovations", 
            email : "contact@appaxisinnovations.tn",
            location : "Tunisie,Ariena Center Escalier C",
            shortdescription : "Appaxis Innovations est une entreprise spécialisée dans le développement web ,mobile et E-commerce, ainsi que dans le design avec Figma pour les nouveaux start-up.",
            description: "Appaxis Innovations est une entreprise spécialisée dans le développement web ,mobile et E-commerce, ainsi que dans le design avec Figma pour les nouveaux start-up.Nous proposons des solutions innovantes et personnalisées pour répondre à vos besoins numériques. Notre équipe d'experts est dévouée à créer des expériences en ligne exceptionnelles pour votre entreprise.",
            sujet : "",
            Images : ["https://i.ibb.co/nBFBHYL/thumbnail-logo-appaxis-75c6b87b65.jpg"], 
            linkDin : "https://www.linkedin.com/company/appaxis/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/19Z--bqIRNDSa0qe55gpkG976_B2DKFRh/view" , 
            pfeBook2024:"",
            web:"https://appaxisinnovations.tn/",
            long:"36.85802290467083",
            lat:"10.18962003507907",
         },

         {
            name: "Arcana Soft", 
            email : "contact@arcana-soft.com",
            location : "Rue D'Alexandrie, Ben Arous 2063",
            shortdescription : "Arcana est une équipe de professionnels motivés et talentueux, spécialisée dans le développement de projets web sur mesure en Tunisie... ",
            description: "Nous avons plus années d'expertiseà notre actif et nous sommes déterminés à mettre en place un system de ERP fiable et à créer des applications web , mobiles et desktop personnalisées qui répondront parfaitement aux besoins et exigences de nos clients. Nous sommes là pour accompagner nos clients à chaque étape du processus de développement, depuis la phase de test jusqu'aux premiers mois d'utilisation de l'outil. Nous sommes passionnés par notre travail et nous sommes fiers de la confiance que nos clients nous accordent",
            sujet : "",
            Images : ["https://i.ibb.co/VWCVf6c/2023-10-25.png"], 
            linkDin : "https://www.linkedin.com/company/arcana-soft/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/posts/arcana-soft_pfe-book-arcana-soft-activity-7124701118684672000-Fpu7/?utm_source=share&utm_medium=member_desktop" , 
            pfeBook2024:"",
            web:"https://arcana-soft.com/",
            long:"36.74352425539693",
            lat:"10.253877498520426",
         },
       
         {
            name: "ARSII Association", 
            email : "contact@arsii.org",
            location : "Bureau 502 - Imm. Louzir, Avenue Palestine, Sahloul Sousse, 4054",
            shortdescription : "L'Association de Recherche Scientifique et Innovation en Informatique (ARSII) est une association scientifique, fondée en mai 2016 par de jeunes enseignants-chercheurs en informatique...",
            description: "L'ARSII a pour objectif de contribuer au soutien de la recherche scientifique dans le domaine des technologies de l'information et de l'innovation, à la proposition, la supervision et le suivi de projets innovants, à la coopération et la collaboration avec les partenaires socio-économiques aux niveaux national et international, au rapprochement de la recherche scientifique et du monde académique avec l'industrie, au soutien à l'intégration des étudiants dans le milieu professionnel, ainsi qu'à l'organisation d'événements scientifiques aux niveaux national et international.",
            sujet : "",
            Images : ["https://i.ibb.co/7RkBrsF/28424070-1654050127995289-7086724902485942110-o.jpg","https://i.ibb.co/WKcTGVv/15123112-1195584257187356-4803166209063809791-o.jpg"], 
            linkDin : "https://www.linkedin.com/company/association-of-scientific-research-and-innovation-in-computer-science-arsii/posts/?feedView=all" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7142249308619268096/" , 
            pfeBook2024:"",
            web:"http://www.arsii.org",
            long:"35.843412154191846",
            lat:"10.595871336665608",
         },

       


// long lat correct here !
         {
            name: "Timsoft Group", 
            email : "contact@timsoft-group.com",
            location : "Rue Lac Loch Ness, Tunis 1053 Les berges du lac 1",
            shortdescription : "Timsoft, votre partenaire clé dans la transformation digitale du Retail, excelle dans plus de 35 pays à travers le globe, fort d'une présence de proximité via nos bureaux en France, en Tunisie et au Maroc.",
            description: "Le groupe possède une vaste expérience dans les solutions logicielles B2B en tant que développeur et intégrateur d'ERP. Timsoft compte plus de 320 professionnels et plus de 1400 projets livrés. Nos 600 clients, principalement issus des secteurs du retail et de la mode, sont présents dans plus de 30 pays, avec une majorité en Europe et au Moyen-Orient.",
            sujet : "",
            Images : ["https://i.postimg.cc/N00nLz09/timsoftgroup-logo.jpg","https://i.postimg.cc/DzYMGPWC/468A0044.jpg"], 
            linkDin : "https://www.linkedin.com/company/timsoftgroup/about/" ,
            pfeBook2023:"https://www.linkedin.com/feed/update/urn:li:activity:7138522865838002178/" , 
            pfeBook2024:"",
            web:"https://timsoft-group.com/",
            long:"36.83330732262236",
            lat:"10.238547008383229",
         },


         {
            name: "PURA", 
            email : "contact.purasolutions@gmail.com",
            location : "Pôle technologique de Sousse, Route de Ceinture Sahloul",
            shortdescription : "PURA Solutions est une startup tunisienne spécialisée dans le développement de solutions matérielles et logicielles de pointe pour le secteur médical et au-delà.",
            description: "Chez PURA Solutions, notre dévouement à la technologie et à l'innovation s'étend à la création de solutions sur mesure, à la fois logicielles et matérielles, spécifiquement adaptées au secteur médical .",
            sujet : "",
            Images : ["https://i.postimg.cc/JzbG2p3F/images-1.png"], 
            linkDin : "https://www.linkedin.com/company/pura-solutions/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1xI4j6SuNOIJFv4mu0YC5HhBzaUnoXej4/view?usp=sharing" , 
            pfeBook2024:"",
            web:"http://pura-tech.com/",
            long:"35.820596961383636",
            lat:"10.593096870260121",
         },




         {
            name: "PLM RESSOURCES", 
            email : "info@allplm.com",
            location : "126 Rue IBN Khaldoun, Bizerte",
            shortdescription : "PLM RESSOURCES GMBH est une société allemande,partenaire officiel de siemens digital industries software dans l’Afrique du Nord",
            description: "PLM RESSOURCES est spécialisé dans la transformation digitale des entreprises et des institutions, et ce dans la région du Maghreb. Se structure autour d’un bureau d’étude d’ingénierie mécanique et développement informatique. Elle accompagne ses clients dans leurs transformations vers la digitalisation et l'Industrie 4.0. .",
            sujet : "",
            Images : ["https://i.postimg.cc/RZFvcGsf/2023-09-29.jpg"], 
            linkDin : "https://www.linkedin.com/company/plm-ressources-company/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1a3-YzjGcb9zHHBKmrqL-9T2a58ujFF-U/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.allplm.com/",
            long:"37.27443710184872",
            lat:"9.868745198430371",
         },

         
         {
            name: "ASQII", 
            email : "contact@asqii.tn",
            location : "Rue Ibn Battouta, Le Kram, Tunisia",
            shortdescription : "ASQII est une startup Healthtech dédiée à l'exploitation de la digitalisation, de l'analyse des données et de l'automatisation des processus pour améliorer les soins contre le cancer.",
            description: "ASQII est une startup Healthtech dédiée à l'exploitation de la digitalisation, de l'analyse des données et de l'automatisation des processus pour améliorer les soins contre le cancer. Notre mission est d'offrir aux patients une expérience de santé optimale grâce à l'utilisation des technologies de pointe.",
            sujet : "",
            Images : ["https://i.postimg.cc/Qt4P2Gs8/asqii-logo.jpg"], 
            linkDin : "https://www.linkedin.com/company/asqii/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1_kFsXHBRtGHjKjJVQC6IqNTWUzCe9Lzb/view" , 
            pfeBook2024:"",
            web:": www.asqii.tn",
            long:"36.837135407949994",
            lat:"10.202148040482378",
         },


         {
            name: "AxeFinance", 
            email : "info@axefinance.com",
            location : "Tunis: Rue du lac Huron,1053 Les Berges du Lac",
            shortdescription : " Des prêteurs mondiaux tels que Société Générale, Al Rajhi Bank, First Abu Dhabi Bank, Abu Dhabi Commercial Bank, Vietnam International Bank et Fidelity Bank ont fait confiance à Axe Finance.",
            description: "Fondée en 2004, Axe Finance est un fournisseur de logiciels de premier plan à l'échelle mondiale, spécialisé dans l'automatisation des risques de crédit pour les prêteurs souhaitant offrir une expérience de financement omnicanal efficace, compétitive et fluide. AxeFinance a développé Axe Credit Portal, une solution innovante, alimentée par l'IA, conçue pour automatiser l'ensemble du cycle de vie du crédit, depuis la connaissance du client (KYC) jusqu'au service, en passant par l'octroi, le scoring de crédit et la prise de décision automatique.",
            sujet : "",
            Images : ["https://i.postimg.cc/g2hxrmB7/axe1.jpg,https://i.postimg.cc/ZK29TCj3/crop-img-98a1bb6d1d790a3987e6ebc8975c5bf4.jpg"], 
            linkDin : "https://www.linkedin.com/company/axe-finance/?originalSubdomain=fr" ,
            pfeBook2023:"https://drive.google.com/file/d/1smsr7C9CCM1mygQcxAtUqrJ_KTx9XOuA/view" , 
            pfeBook2024:"",
            web:"www.axefinance.com",
            long:"36.83662604063392",
            lat:"10.248013200000003",
         },

         {
            name: "Bee Coders", 
            email : "contact@9antra.tn",
            location : "Technopole El Ghazela",
            shortdescription : " Fondée en 2020, Bee Coders est une entreprise de services numériques dédiée à la création de solutions digitales uniques et sur mesure qui ont un véritable impact.",
            description: "Axée sur l'innovation et engagée envers l'excellence, nous nous spécialisons dans la livraison de produits et d'expériences numériques qui redéfinissent les standards de l'industrie et mettent nos clients sur la voie du succès numérique. Depuis sa création, Bee Coders cultive une culture d'entreprise centrée sur la flexibilité, le soutien et la qualité. Ces principes représentent l'essence même des valeurs fondamentales de l'entreprise.",
            sujet : "",
            Images : ["https://i.postimg.cc/h4JsM7JQ/1666711282616.jpg"], 
            linkDin : "https://www.linkedin.com/company/bee-coders/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1bSQ1D0q3DcE1Llwhb3-pDIodXV2VJ6g-/view" , 
            pfeBook2024:"",
            web:"https://www.beecoders.tn/",
            long:"36.89617015153085",
            lat:"10.186281826863004",
         },
         {
            name: "BePrimetech", 
            email : "stage@beprimetech.com",
            location : "Route de Tunis, Km 4 Markez Bouasida, Sfax 3031",
            shortdescription : " BePrimeTech est une Start-Up ayant comme spécialité la création et le développement des solutions logicielles adaptées à la croissance perpétuelle de la vie professionnelle",
            description: "BePrimeTech garantit un accompagnement et un suivi de qualité lors de la création de solutions sur-mesure grâce à nos départements performants.Nous cherchons toujours à mettre l'accent sur des profils Passionnés, Bosseurs, Créatifs et Ambitieux... En tant qu'éditeur de solutions technologiques, BePrimeTech se distingue par la création d'un produit axé sur la digitalisation de l'activité hôtelière et de la voyagerie.",
            sujet : "",
            Images : ["https://i.postimg.cc/CKTpLVWm/1649847427237.jpg"], 
            linkDin : "https://www.linkedin.com/company/be-prime-tech/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1eWk8W0lfBhYgNAstwsv4BAWYkin58M7l/view" , 
            pfeBook2024:"",
            web:"https://beprimetech.com/",
            long:"34.778797802093244",
            lat:"10.760595444176452",
         },
         
         {
            name: "Luceor", 
            email : "support@luceor.com",
            location : "Technopark Elghazela, Tunis",
            shortdescription : " Pour les organisations ayant des besoins de connectivité spécialisés, les produits de Luceor simplifient la prise de décision et permettent de combiner au mieux couverture, bande passante, confidentialité, sécurité et coût.",
            description: "La technologie hautement adaptable de Luceor offre un accès intelligent à un ensemble d'options réseau, garantissant une connectivité résiliente et ininterrompue, où que vous soyez et à tout moment. Avec plus de 450 déploiements pour des systèmes d'urgence, des événements majeurs et des applications militaires dans 15 pays différents, Luceor est un leader mondial dans les applications de connectivité spécialisée. Plus de 100 villes, gouvernements fédéraux et entreprises font confiance à Luceor pour répondre à leurs besoins en réseaux critiques.",
            sujet : "",
            Images : ["https://i.postimg.cc/90ZP7b1s/843-1669728062.png","https://i.postimg.cc/jq74mqKv/1700670303289.jpg"], 
            linkDin : "https://www.linkedin.com/company/luceor/?originalSubdomain=fr" ,
            pfeBook2023:"https://drive.google.com/file/d/1ujx2IzNlL8R_o-KPz3mRGv9FeHRElmnf/view?usp=sharing" , 
            pfeBook2024:"",
            web:"http://www.luceor.com",
            long:"36.89564925636406",
            lat:"10.186032415932166",
         },



         {
            name: "AYMAX", 
            email : "recrute@aymax.fr",
            location : "2ème étage, Bloc B de Immeuble Youssef Towers - Avenue de Dinars 1053, Tunis 1053",
            shortdescription : " Aymax est une entreprise de services du numérique (E.S.N.) internationale experte dans le conseil, le développement d’applications digitales, de solutions web et l’intégration de solutions ERP/SAP.",
            description: "Créée en 2014 à Paris par un groupe de consultants·tes possédant une vision moderne et flexible du monde du conseil SAP, nous sommes aujourd’hui plus de 200 collaborateurs·rices, en France, Tunisie, Egypte et en Belgique. Notre croissance exponentielle en 10 ans est le fruit de nos collaborations et de l’interconnexion de nos bureaux. Par notre proximité, nous nous engageons à soutenir chaque membre de notre équipe, pour l’accompagner dans le développement de ses compétences aussi bien métiers, qu’humaine et interpersonnelle.",

            sujet : "",
            Images : ["https://i.postimg.cc/vTvNFG9P/2023-09-12.png","https://i.postimg.cc/ZYPgyxgr/DSC-6291.jpg"], 
            linkDin : "https://www.linkedin.com/company/aymax-consulting/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1A0gwCaEk-2QLVvMJx9on53DR1fY64GKd/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://aymax.fr/",
            long:"36.847400077396856",
            lat:"10.268412498676616",
         },


         {
            name: "WildKard", 
            email : "Recrutement@wildkard.tn",
            location : "Cebalet Ben Ammar, Route de Bizerte Km 17, Ariana Tunis, 2032",
            description: "Wildkard est le premier site de vente en ligne Tunisie , L’endroit où vous trouvez tout ce dont vous avez besoin, de la mode pour hommes, femmes et enfants aux chaussures et survêtements, en passant par la nutrition sportive, les soins de la peau et les produits de beauté.",
            shortdescription : " Wildkard est le premier site de vente en ligne Tunisie , L’endroit où vous trouvez tout ce dont vous avez besoin, de la mode pour hommes, femmes et enfants aux chaussures et survêtements, en passant par la nutrition sportive, les soins de la peau et les produits de beauté.",

            sujet : "",
            Images : ["https://i.postimg.cc/3JLdY6XN/images-2.png"], 
            linkDin : "https://www.linkedin.com/company/wildkard/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1JJ9r6VQsVqlGDm2sBj0GTxjgQ91xnUUB/view?usp=sharing" , 
            pfeBook2024:"",
            web:"http://www.wildkard.tn",
            long:"36.90389434031025",
            lat:"10.108805816938188",
         },
         



         
        {
            name: "Valeo", 
            email : "cda.recrutement-valeo-tn.mailbox@valeo.com",
            location : "Q65J+J4J، Rue Des Métaux, Ben Arous 2013",
            description: "Valeo est l’une des premières multinationales installées en Tunisie et ce depuis 36 ans. Opérant avec 4 sites répartis sur le territoire tunisien, avec près de 2000 employés hautement qualifiés, Valeo Tunisie livre des produits pour les plus grands constructeurs automobiles dans le monde.Valeo Tunisie a débuté avec une unité de production basée à Jedeida avec seulement 52 employés. Avec un personnel réduit mais très professionnel, le site a réussi à livrer ses produits de qualité et à satisfaire ses clients. Les activités de Valeo Tunisie ont commencé en 1984 avec le Groupe “Powertrain Systems” (PTS), en installant le premier site “Valeo Embrayages Tunisie” qui produit deux produits phares, les embrayages et les volants moteurs.",
            shortdescription : " Valeo est l’une des premières multinationales installées en Tunisie et ce depuis 36 ans.",

            sujet : "",
            Images : ["https://i.postimg.cc/029QVYcD/tunisia-country-page-valeo-01-1600x698-acf-cropped.jpg","https://i.postimg.cc/15Mz28jT/tunisia-country-page-valeo-08.jpg"], 
            linkDin : "https://www.linkedin.com/company/valeo/" ,
            pfeBook2023:"https://drive.google.com/file/d/1Q5AXveBKjowoyZTnb7dx2vUeaa-4uXzv/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.valeo.com/fr/tunisie/",
            long:"36.75932697067812",
            lat:"10.23028083519563",
         },
         

         
         {
            name: "VTL", 
            email : "Recrutement@vtl.com.tn",
            location : "Zone Indus tri e l l e RUE DE KORBA Km2 -8080 - Menz e l Temime",
            description: "Avec 9 sites répartis entre Menzel Temime et Menzel Bouzelfa, VTL n'est pas une entreprise textile ordinaire. Elle comprend six unités de production de vêtements, une unité d'impression sérigraphique, ainsi qu'une unité dédiée au tissage, au tricotage et à la finition textile C'est exact, nous couvrons tous les aspects ! Et la meilleure partie ? Nous sommes une entreprise textile entièrement intégrée verticalement, spécialisée dans l'exportation. Cela signifie que nous proposons un ensemble complet de services à nos clients, comprenant les matières premières, le développement et la conception de produits, la production, la finition, la logistique, et bien plus encore.",
            shortdescription : " VTL est l'une des principales entreprises textiles non seulement en Tunisie mais aussi dans la région méditerranéenne.",

            sujet : "",
            Images : ["https://i.postimg.cc/j5ZryVdJ/images-2.jpg"], 
            linkDin : "https://www.linkedin.com/company/vtl-menzel-temime/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1u951qpxRR7CDQ_xuowMEHv3JcfzoHrEu/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.linkedin.com/company/vtl-menzel-temime/about/",
            long:"36.76028780320655",
            lat:"10.972818262610376",
         },

        

         {
            name: "Tnker", 
            email : "tnker.tn@gmail.com",
            location : "Borj Baccouche,Residence Alya, Ariana",
            description: "Pendant ce temps, pour les prestataires de services, Tnker agit comme un catalyseur numérique, offrant une visibilité en ligne accrue et un outil sophistiqué de suivi des tâches. Cela permet aux prestataires d'améliorer leur activité, d'optimiser leurs flux de travail et de gérer efficacement leurs tâches, ce qui entraîne une amélioration globale de leurs projets professionnels.",
            shortdescription : "Tnker est une application mobile à la pointe de la technologie qui utilise des algorithmes de recommandation et de réseautage social pour connecter de manière fluide les personnes en quête de services avec des prestataires qualifiés.",

            sujet : "",
            Images : ["https://i.postimg.cc/wjvbcrNP/1652989035215.jpg"], 
            linkDin : "https://www.linkedin.com/company/tnkertn/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1b0gYPRwKBktvKUEgm_sD0wy-fpWlP_rn/view" , 
            pfeBook2024:"",
            web:"https://tnker.tn/",
            long:"36.85695203642154",
            lat:"10.198924638031269",
         },
         


         {
            name: "TADREEX", 
            email : "contact@tadreex.com",
            location : "Novation City, Technopole de Sousse Sousse, 4051, Sousse, TN",
            description: "Fondée en 2021,TadreeX est spécialisée dans la création de formations professionnelles révolutionnaires en utilisant la réalité virtuelle. Nous exploitons la puissance de cette technologie pour développer une expérience de formation inédite en matière de sécurité et de santé au travail.",
            shortdescription : "Fondée en 2021,TadreeX est spécialisée dans la création de formations professionnelles révolutionnaires en utilisant la réalité virtuelle. Nous exploitons la puissance de cette technologie pour développer une expérience de formation inédite en matière de sécurité et de santé au travail.",

            sujet : "",
            Images : ["https://i.postimg.cc/x1J3dVM0/images-3.png"], 
            linkDin : "https://www.linkedin.com/company/tadreex/" ,
            pfeBook2023:"https://drive.google.com/file/d/1ZLoPOnhPVEiClIN_vHyenj9VfpXzmBeA/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://tadreex58b3ba199b.wordpress.com/",
            long:"35.81647694854135",
            lat:"10.591375701544361",
         },
         
         {
            name: "StreamLink", 
            email : "contact@streamlink.fr",
            location : "Immeuble Golden Tower Bloc A1.9 1082 Centre Urbain-Nord Ariana El Menzeh, Tunisie.",
            description: "Streamlink est un cabinet de conseil et de services technologiques, créé en 2017. nos services conviennent à tous types d'applications incluant les ordinateurs centraux, les applications web ou de développement « maison » ainsi que les logiciels ERP/CRM.",
            shortdescription : "spécialisée dans le digital, SAP et le BI, est présente dans les domaines de la banque, de la finance, de l'assurance, du service et de l'industrie. ",

            sujet : "",
            Images : ["https://i.postimg.cc/PqGyF6BK/streamlink-sas-logo.jpg","https://postimg.cc/1g3wwN47"], 
            linkDin : "https://www.linkedin.com/company/streamlink-sas/?trk=ppro_cprof&originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1RgIJeLpyFo3xvw2tolXL1sNA-wzjk3BW/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.streamlink.fr/",
            long:"36.84900491993795",
            lat:"10.19975063904588",
         },

         {
            name: "STMicroelectronics", 
            email : "non disponible",
            location : "Bloc B33, Elgazela Technopark, Cedex 2088",
            description: "ST est un leader mondial des semi-conducteurs, proposant des produits et des solutions intelligents et économes en énergie qui alimentent les technologies au cœur de la vie quotidienne. Les produits de ST sont omniprésents aujourd'hui et, avec nos clients, nous rendons possible une conduite plus intelligente, ainsi que des usines, des villes et des maisons plus intelligentes, tout en accompagnant la prochaine génération de dispositifs mobiles et de l'Internet des objets. En tirant le meilleur parti de la technologie pour améliorer la vie, ST se veut synonyme de « life.augmented ».",
            shortdescription : "ST est un leader mondial des semi-conducteurs, proposant des produits et des solutions intelligents et économes en énergie qui alimentent les technologies au cœur de la vie quotidienne. ",

            sujet : "",
            Images : ["https://i.postimg.cc/P5rG6qn2/logo-20140521-101306.jpg"], 
            linkDin : "https://www.linkedin.com/company/stmicroelectronics/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1RgIJeLpyFo3xvw2tolXL1sNA-wzjk3BW/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.st.com/content/st_com/en.html?src=linkedin",
            long:"36.89545897934762",
            lat:"10.187151850104936",
         },


         {
            name: "SECURAS", 
            email : "securas.sousse@planet.tn",
            location : "19, Rue de l'artisanat, Tunis",
            description: "SECURAS s’assure en permanence des qualités morales professionnelles de ses cadres afin de réaliser ses missions avec l’absolue impartialité.Notre CompétenceLes missions de SECURAS sont réalisées par des ingénieurs Séniors d’une longue expérience encadrés par la Direction Technique. SECURAS s’est toujours engagé dans le développement permanent de la compétence de ses cadres à travers la formation continue et le retour sur expérience.",
            shortdescription : "SECURAS TECHNOLOGIES est une Startup qui propose des solutions et des services de Cybersécurité et Cyber Threat Intelligence permettant à la fois de détecter et prévenir les attaques et les menaces cyber. ",

            sujet : "",
            Images : ["https://i.postimg.cc/7hCMWCBd/securas-sas-logo.jpg"], 
            linkDin : "https://www.linkedin.com/company/securas/?originalSubdomain=tn" ,
            pfeBook2023:"https://drive.google.com/file/d/1fBgTJTht-vdEFEw47pxGRReIKLYGYbUh/view?usp=sharing" , 
            pfeBook2024:"",
            web:"http://www.securas.tn/",
            long:"36.85280250096342",
            lat:"10.20460658630593",
         },
         
         {
            name: "Tradrly", 
            email : "tradrly.job@gmail.com",
            location : "Mahdia , Tunisie",
            description: "Notre mission est de donner aux entreprises du monde entier les moyens de concrétiser leurs idées visionnaires. Avec une équipe dynamique d’experts, dévouée à repousser les limites de la transformation numérique, nous nous spécialisons dans le développement d’applications sur mesure, adaptées aux besoins uniques de notre clientèle diversifiée. Des startups aux entreprises bien établies, notre objectif est de faciliter des parcours numériques fluides, en veillant à ce que chaque projet que nous entreprenons dépasse les attentes de nos clients. Rejoignez-nous pour redéfinir l’avenir de la technologie, projet par projet.",
            shortdescription : "Basée au cœur vibrant de Mahdia, en Tunisie, notre startup innovante se positionne à l’avant-garde de la création de solutions de pointe qui allient le meilleur des technologies web, mobile et de l’intelligence artificielle.",

            sujet : "",
            Images : ["https://i.postimg.cc/GmKwfXhs/tradrly-tn-cover.jpg"], 
            linkDin : "https://www.linkedin.com/company/tradrly-tn/" ,
            pfeBook2023:"" , 
            pfeBook2024:"https://www.linkedin.com/posts/salah-sammari_pfe-book-ugcPost-7254775990642475008-vdwJ/?utm_source=share&utm_medium=member_desktop&fbclid=IwY2xjawGGWIFleHRuA2FlbQIxMAABHRGR4X9X6IG71MFPEwKQGIN-Ee4KcrepX7HZT7DQD9cuMCm_XggDWx7BEg_aem_EQYPPUfa7nxkwAR1kxKw5g",
            web:"Non disponible",
            long:"35.504043035486035",
            lat:" 11.068138012994556",
         },


         {
            name: "Safran", 
            email : "catherine.malek@safrangroup.com",
            location : "Route de Tunis km 6",
            description: "Safran S.A. est une multinationale française spécialisée dans l'aérospatiale et la défense, qui conçoit, développe et fabrique des moteurs d'avions, des moteurs d'hélicoptères, des systèmes de propulsion spatiale ainsi que divers autres équipements aéronautiques et militaires. L'entreprise est née en 2005 de la fusion entre SNECMA et le spécialiste de l'électronique de défense SAGEM. L'acquisition de Zodiac Aerospace par Safran en 2018 a considérablement élargi ses activités dans le domaine de l'aéronautique.",
            shortdescription : "Safran S.A. est une multinationale française spécialisée dans l'aérospatiale et la défense, qui conçoit, développe et fabrique des moteurs d'avions, des moteurs d'hélicoptères, des systèmes de propulsion spatiale ainsi que divers autres équipements aéronautiques et militaires. ",

            sujet : "",
            Images : ["https://i.postimg.cc/Bn4MDbns/logo-14803-20190823-111418.png"], 
            linkDin : "https://www.linkedin.com/in/safran-tunisia-6048b5121/" ,
            pfeBook2023:"https://drive.google.com/file/d/1fpyQ89c3C-KnjT6OIO6Jm4d1xVyj-4tO/view?usp=sharing" , 
            pfeBook2024:"",
            web:"https://www.safran-group.com/fr/pays/tunisie",
            long:"36.69798098408839",
            lat:"10.445718737311415",
         },
         
         
        ]
      })
    }
  }